export const FETCH_UNITTYPES = 'FETCH_UNITTYPES';
export const DELETE_UNITTYPE = 'DELETE_UNITTYPE';
export const UPDATE_UNITTYPE = 'UPDATE_UNITTYPE';
export const CREATE_UNITTYPE = 'CREATE_UNITTYPE';
